project:
  type: website
  output-dir: ../docs


website:
  page-navigation: true
  search: false
  page-footer:
    border: false
    background: transparent
    foreground: DimGray
    #left: Left content
    #right: Right content
  navbar:
    background: transparent
    pinned: true
    left:
      - file: index.qmd
        text: Home
      - file: "ticketmaster.qmd#intro"
        text: Introduction
      - text: Analysis
        menu:
        - text: Exploratory Data Analysis
          href: "ticketmaster.qmd#eda"
        - text: Hypothesis Testing
          href: "ticketmaster.qmd#hypothesis"
        - text: Linear Regression
          href: "ticketmaster.qmd#linear"
        - text: Results
          href: "ticketmaster.qmd#results"
      - text: Conclusion
        href: "ticketmaster.qmd#conclusion"


        

format:
  html:
    theme: 
      - styles.scss
    toc: false

editor: visual
